### ISSUE TITLE
frontend resetpassword and activation url

### ISSUE THREAD

**Issue by uggyk** [aqilix/zf3-apigilty-oauth2#7]
Dear Mr. Dolly, 

I have a doubt regarding the url for the reset password and activation url. I do not see any code for these sites.

correct me if I am wrong, but from the code what I understand is that after the user signs up, the user would then get an email with an activation url https://aqilix.xyz/user/activation/:code that says i.e. "Your Account has been registered", 

and if the user sent a resetpassword user would get an email with the resetpassword URL, now where would the resetpassword form would be? do i need to develop it myself? or does this source code handle it by itself?

I know they are located in project.global.php,

```
'sites' => [
           'reset_password_url' => 'https://aqilix.xyz/user/resetpassword/:code',
           'activation_url' => 'https://aqilix.xyz/user/activation/:code',
```

my question is, do I need to write a code for them? or are they included?

Regards,
uggy

**Comment by dollyaswin** [comment]
Hi, 

Thanks for your question. That is just URL. The URL not contain any form inside it. You can change the form as you like. Because I think, the web can be different from this API. So, in the API I just give URL, and the form is the another part.
If you develop a website using Single Page Application, the form is not handle by the API. It just process data sent by form.

Thanks

**Comment by uggyk** [comment]
great. I think I will just handle all of that through the application frontend. using the rpc provided.


thanks Mr. Dolly!
